repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: double-quote-string-fixer
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    -   id: isort

-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-unused-variable']

- repo: https://github.com/prettier/prettier
  rev: "v1.15.0"
  hooks:
    - id: prettier
