# Generated by Django 3.1.2 on 2020-10-29 22:32

import customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(help_text='Contact Numbers that should start with one of [789] and max length to be 10 digits', max_length=10, unique=True, validators=[customers.validators.validate_contact_number])),
                ('date_of_birth', models.DateField(help_text='Date of birth of customer validation to check if user is above 18 years of age.', validators=[customers.validators.validate_date_of_birth])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
