# Generated by Django 3.1.2 on 2020-10-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Compact'), (2, 'Premium'), (3, 'Minivan')], default=2, help_text='To which category of cars this individual car belongs to.')),
                ('number', models.CharField(help_text='An human readable unique identifier or number for this car.', max_length=10)),
                ('is_hired', models.BooleanField(default=False, help_text='Represents this car is currently hired if set to true otherwise false')),
                ('current_milage', models.FloatField(help_text='Represents the current milage of the car')),
            ],
        ),
    ]
