# Generated by Django 3.1.2 on 2020-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(help_text='An human readable unique identifier or number for this car.', max_length=10, unique=True),
        ),
    ]
